### PR TITLE
add `EnableRegistry` for eventloop, fix #64

### LINKED ISSUE #64: [Feature Request] Add a option for disable the `require` method when using EventLoop
I want to use eventloop, but I don't want require because I don't want the script can access my filesystem.

I can make a source loader that will always return an error, but the built-in modules such as `node:console` could still be required.  
It's not a such big issue, but I already implement my own console object, so I don't want the script use the other.

### PR DESCRIPTION
**Pull request by zyxkad**

### CODE REVIEW

**Comment by zyxkad** [comment]
Hi @dop251 can you merge this pull request? Or is there any issue on this pr that I have to fix?

**Comment by dop251** [comment]
I'm not sure this option is necessary. You can redefine or completely remove the `require` function to get the desired result.

**Comment by zyxkad** [comment]
> I'm not sure this option is necessary. You can redefine or completely remove the `require` function to get the desired result.

I believe it is, if remove something will mean disable them, why do we need `EnableConsole` lol

**Comment by dop251** [comment]
In hindsight we probably didn't, but since it's already there I'm not going to remove it. What I definitely don't want to end up with is having an EventLoop option for every single Runtime or Registry option. It's also becoming quite messy due to options' inter-dependencies, for example with your latest change, `NewEventLoop(EnableRegistry(false), EnableConsole(true))` will panic.

What about adding something like NewVanillaEventLoop() which does not do anything to the Runtime other than adding the loop-specific functions (setTimeout, etc.)? This will allow manual configuration of the Runtime and will cover all corner cases.

**Pull request closed without merging**
