### PR TITLE
Fix event loop hanging in foreground

### PR DESCRIPTION
**Pull request by Cretezy**

### CODE REVIEW

**Comment by dop251** [comment]
Hi @Cretezy. How did you encounter this problem?

**Comment by Cretezy** [comment]
Was having some issues running the event loop after execution with no timers/intervals, this fixed it

**Comment by dop251** [comment]
Ok, just wanted to make sure you don't use Run() instead of RunOnLoop() while the loop is running. I will add some docs about this.

**Comment by Cretezy** [comment]
Nice work. I have a fetch implementation I might submit when it's complete, I'm not using require directly (would be nice to decouple the event loop and require so it's easier to use as a standalone module)

**Comment by tmm1** [comment]
@Cretezy do you have a `fetch` you plan to share?

**Pull request closed without merging**
